### ISSUE TITLE
MrCrayFish's Gun Mod Aiming is Off

### ISSUE THREAD

**Issue by Barerock** [tr7zw/FirstPersonModel#357]
Forge 43.2.3, 1.19.2

All guns related to the Gun Mod are offset by around -16 units on X axis and some amount on the Y axis. The X axis is easily fixed with the adjustment in mod options, but the guns are still so low on the Y axis that aiming is completely wrong.

Example image while I'm crouching and aimed directly at the bullseye without aiming, this sets up where my ironsight/scope SHOULD be when aiming. Sneaking and Standing X offset is set to -16
![image](https://github.com/tr7zw/FirstPersonModel/assets/38869993/583e88f7-45d0-4e92-854d-2d0ecaa58b67)
![image](https://github.com/tr7zw/FirstPersonModel/assets/38869993/3e2b16d1-0227-475d-ae8d-3aeca6a5905a)
Above image demonstrates Y axis being too high while sneaking and aiming.
Below image demonstrates Y axis being too low while standing and aiming.
![2023-05-29_20 25 05](https://github.com/tr7zw/FirstPersonModel/assets/38869993/241c1c55-5e2a-42a3-bc28-f9c076ab438a)
The crosshair IS in the middle of the target, but when aiming this is disrupted.

Also is version 2.2.0 of First Person Model updated to add compatibility for MrCrayFish's Gun Mod regarding the third person gun/arm still existing when holding one in first person? When I swap to Vanilla arms option ON, the 2nd arm shows up. The changelog does state that that problem has been fixed in this version, so I'm a tad confused. This is in reference to #266 and others.

Thanks, super ambient and I like it -- hope these issues can be resolved one way or another :)

**Comment by tr7zw** [comment]
It was basically never compatible and can't be. Your best bet is adding it to the auto vanilla hands so the mod turns off while holding one of these items.

**Comment by Barerock** [comment]
Awe shucks, that's unfortunate. I'm not sure how to add it to that, is there a tutorial I can follow?

**Comment by Barerock** [comment]
Do numbers affect this config, such as adding something named 9a91? I'm unfamiliar with how JSON works, but my notepad++ shows that numbered entries are wrong.

**Comment by tr7zw** [comment]
Numbers work just fine. You just need to make sure that each entry is in `"` with a `,` between entries. The last entry should not have a `,` at the end. So ``"a", "b", "c"``.

**Comment by Barerock** [comment]
Got it, I've done similar with JSON for other games but didn't know if communication with Java made any exceptions. Thanks for your help, and keep up the good work!

**Comment by Barerock** [comment]
Unfortunately adding every gun from Additional Guns, Project Arsenal, and MrCrayFish's Gun Mod (CGM), the 2nd arm shows up as referenced in another bug report.
![image](https://github.com/tr7zw/FirstPersonModel/assets/38869993/4ac52d86-6dbb-4cfe-a928-a62b84522244)
I doubt this is an issue with CGM or its addons, considering the entire model structure isn't added by it or altered by it. 

It was worth a try. I'll just have to live with never aiming again until this is patched on one or the other side. Thanks again :)

**Comment by Barerock** [comment]
Other issue is #343

**Comment by tr7zw** [comment]
> I doubt this is an issue with CGM

Well, if it renders the gun twice with vanilla hands, then that's an issue with CGM. Honestly, that mod caused sooo many issues already(also with my other mods), I'm not sure why people use it at all.

**Comment by Barerock** [comment]
I haven't seen any issue with other mods out of a couple hundred. How would it be on CGM's end if THIS mod keeps rendering the model. The 2nd arm seems to be from this mod's interpretation of where things should be.

**Comment by tr7zw** [comment]
The arms and item in hand are turned off, and CGM still renders the weapon. So far worked with any other mod, except apparently create which has the inverse issue(the first-person model renders when turned off).

**Comment by Barerock** [comment]
Welp. Guess we leave it up to CrayFish. Have fun and good luck :D

**Comment by tr7zw** [comment]
I mean, would be neat to fix this issue after over 2 years with CrayFish, but haven't had any contact with him so far.

**Comment by Barerock** [comment]
He closed the issue on his end stating it should be compatible with 1.19+, which clearly isn't true. So he evidently doesn't actually know it's still broken. He blamed the rendering platform both mods were using. I am reopening the issue with this tagged. I'll link here when I'm done.

**Comment by tr7zw** [comment]
I think it did work somewhat at some point(the sights not lining up, but otherwise no visual artifacts).

**Comment by Barerock** [comment]
Oh yeah, it looks sick without vanilla hands on, but the sights don't line up. It's functional, but sad.

**Comment by tr7zw** [comment]
I mean, the sights not lining up is not a bug of this mod. Thats just the 3rd person animation of CGM. Nothing I could do about that either way. The only valid bug is that vanilla hands doesn't work correctly.

**Comment by Barerock** [comment]
https://github.com/MrCrayfish/MrCrayfishGunMod/issues/466

**Comment by Barerock** [comment]
Oh yeah, I figured the sights lining up is simply how the vanilla animations settled. It's unfortunate that Minecraft has been built on a pyramid of pre-2000s programming decisions in the modern era.

**Comment by Barerock** [comment]
It gives me Black Mesa vibes, with the monorail NPCs and the way AI was designed.

**Comment by Barerock** [comment]
I guess a solution to that would be adding a black/white list function to raise Y level of camera view by whatever amount just like the X axis changes. That'd probably fix everything with CGM by implementing ability for literal FPS chest cam view.

**Comment by tr7zw** [comment]
I won't touch the camera at all, since that would break the mod with any server. Two options: the 3rd person animation gets lined up with the camera or vanilla hands gets fixed to just show the default CGM first-person animations, hiding the 3rd person entirely.

**Comment by MrCrayfish** [comment]
It's out of scope to support this mod and would require a lot of work since all the animations would need to be super precise to position the weapon correctly, let alone support offsetting all those animations if a scope is on the weapon. Best I can do is look into the gun rendering twice

**Comment by Barerock** [comment]
> 

That'd be excellent if you find the time, both look quite good either way and the only problem holding back both is that render issue.

**Comment by tr7zw** [comment]
When the 3rd person version is correctly hidden during vanilla hands, I'd add the CGM items to the default auto vanilla hands list.

**Comment by Frikandel321** [comment]
Couldn't there be a config option to completely disable the first person model and all other mod features when holding certain items? I personally wouldn't mind the mod only working when not holding a gun, and it might solve the issue. Also, I couldn't find any information about the options in the config file, so there might already be such an option. (I'm not talking about vanilla hands, I figured that one out already)

**Comment by tr7zw** [comment]
> I'm not talking about vanilla hands

You are talking about vanilla hands. 

> Couldn't there be a config option to completely disable the first person model and all other mod features when holding certain items?

And that is already exactly how it should be fixed, and what is not working correctly(see above).

> Also, I couldn't find any information about the options in the config file, so there might already be such an option.

Auto vanilla hands, see above.

**Comment by Frikandel321** [comment]
No, I am not talking about vanilla hands, because with vanilla hands enabled I can still see the rest of my character model with just the hands removed. I think that the double rendering of guns is caused by first person model, and that a config option that could disable all features of the mod could atleast fix the double rendering (vanilla hands doesn't do that, it just disables the hands). 
Also, the other config options are really vague. I can't find any explanation about 'enabled by default', 'render stuck features', or 'force active'.

**Comment by tr7zw** [comment]
> Also, the other config options are really vague. I can't find any explanation about 'enabled by default', 'render stuck features', or 'force active'.

Update to the latest version(1.19.4), then these settings have a tooltip again: https://github.com/tr7zw/FirstPersonModel/blob/1.19.4/Shared/src/main/resources/assets/firstperson/lang/en_us.json

> No, I am not talking about vanilla hands

Yes you are. The double-rendered guns are the bug that this exact issue is trying to fix. After that, you hold the normal vanilla firstperson gun with both hands, and when looking down you see the rest of the body. That's the intended result.

**Comment by MrCrayfish** [comment]
I thought I made some changes that would fix this issue, however upon testing it seems `autoVanillaHands` is not adding my weapons. I can press F6 in the game and it works as intended, however it's not doing that automatically with `autoVanillaHands`.

**Comment by tr7zw** [comment]
Managed to work around issues like this by applying the same "hack" I apply to the head also to the arms when hiding them(moving them a few hundred blocks behind the camera, so anything attaching to them also flies away). This seems to have done the trick to get vanilla arms working as expected(no duplicated guns):
![grafik](https://github.com/tr7zw/FirstPersonModel/assets/5133936/a2aca9f5-e546-439e-9c20-fdfcf42a97f9)

**Comment by Barerock** [comment]
What a funny fix. I love modding. Thanks for continuing to work on this somewhat niche issue, massive move for sure. <3
